### ISSUE TITLE
Comfy Shadow theme leaves spicetify with a black plain background. Unsuable.

### ISSUE THREAD

**Issue by NativeEnma** [ohitstom/comfy-shadow#1]
I really love the way this theme looks and works, and I been trying my best for the past 3 hours to make it work but it just isn't. It just leaves me with a unusable spotify, a black background that doesn't show buttons or nothing just the playing bar at the bottom. Please help, very much appreciated.

![ComfyShadow black background](https://user-images.githubusercontent.com/100346805/155497069-a3965cad-6d66-41eb-b60b-8f477b08675a.png)
![Console ](https://user-images.githubusercontent.com/100346805/155497074-13c32d8f-4e49-43ca-bee8-8dc0f2d16647.png)

**Comment by NativeEnma** [comment]
![Start of Console](https://user-images.githubusercontent.com/100346805/155498217-95eed157-ce5d-41b0-98e5-ff24ecbcb46c.png)

**Comment by ohitstom** [comment]
Hello, so sorry for the late reply, would you be able to join the spicetify discord server and ping me for further troubleshooting?
(Assuming this issue hasnt already been resolved)

https://discord.gg/JFGNeb8C
tom lol#8951

**Comment by NativeEnma** [comment]
My boi Tom, helped me fix this. Turns out there was something wrong with my files.. This theme is great, USE IT!♥.

**Comment by LeonHenning** [comment]
@NativeEnma what did you do to fix the issue?
