### ISSUE TITLE
Preview images do not reflect current state of the theme

### ISSUE THREAD

**Issue by afonsojramos** [ohitstom/comfy-shadow#2]
I love the serious look of this theme, and I'll definitely use it for the next few months, but the preview images did not reflect the current state of the theme at all.

<img width="1840" alt="Screenshot 2022-04-29 at 11 05 00" src="https://user-images.githubusercontent.com/19473034/165924980-3eaf9e3b-722d-4047-9e7c-d3d2af7e9a04.png">

Anyway, love the fact that everything stays hidden by default!

**Comment by ohitstom** [comment]
Would you be able to point out exactly where it does not match? Cause that looks almost identical from where im standing.... I follow comfy updates so unfortunately until its updated theres not much i can do for broken aspects due to the latest update...

**Comment by afonsojramos** [comment]
![image](https://user-images.githubusercontent.com/19473034/166218176-e1e838f2-bfa7-43e7-8ecb-2253ff584939.png)

I mean this image in the readme 😅

**Comment by afonsojramos** [comment]
It's just that you share almost only one screen, which imo doesn't show the full glory of the theme, but nevermind, I'll close the issue if it doesn't make sense to you!
